"""
平台模块路由
返回家庭管理系统的模块目录与路线图
"""
from fastapi import APIRouter

router = APIRouter()

MODULES = [
    {
        "id": "workbench",
        "title": "工作台",
        "status": "ready",
        "category": "core",
        "description": "家庭概览、快捷入口、天气新闻和近期协作动态。",
        "web_route": "/",
        "miniapp_route": "/pages/home/home",
        "owner": "platform",
    },
    {
        "id": "chat",
        "title": "智能对话",
        "status": "ready",
        "category": "core",
        "description": "统一入口，承载家庭助手、记忆和任务交互。",
        "web_route": "/chat",
        "miniapp_route": "/pages/webview/webview",
        "owner": "platform",
    },
    {
        "id": "modules",
        "title": "模块中心",
        "status": "ready",
        "category": "system",
        "description": "统一查看 Web 与小程序覆盖的全部管理模块。",
        "web_route": "/modules",
        "miniapp_route": "/pages/modules/modules",
        "owner": "platform",
    },
    {
        "id": "finance",
        "title": "家庭财务",
        "status": "ready",
        "category": "core",
        "description": "收支记录、月度汇总、趋势分析、分类管理。",
        "web_route": "/finance",
        "miniapp_route": "/pages/webview/webview",
        "owner": "finance",
    },
    {
        "id": "wedding",
        "title": "备婚管理",
        "status": "ready",
        "category": "life",
        "description": "婚礼筹备、预算、待办、供应商、时间线。",
        "web_route": "/modules/wedding",
        "miniapp_route": "/pages/webview/webview",
        "owner": "product",
    },
    {
        "id": "insurance",
        "title": "保险管理",
        "status": "ready",
        "category": "life",
        "description": "保单、到期提醒、保障范围、家庭成员覆盖。",
        "web_route": "/modules/insurance",
        "miniapp_route": "/pages/webview/webview",
        "owner": "product",
    },
    {
        "id": "vehicle",
        "title": "车辆管理",
        "status": "ready",
        "category": "life",
        "description": "保养、年检、保险、加油、违章与费用记录。",
        "web_route": "/modules/vehicle",
        "miniapp_route": "/pages/webview/webview",
        "owner": "product",
    },
    {
        "id": "fitness",
        "title": "健身管理",
        "status": "ready",
        "category": "life",
        "description": "训练计划、身体数据、餐饮记录、目标跟踪。",
        "web_route": "/modules/fitness",
        "miniapp_route": "/pages/webview/webview",
        "owner": "product",
    },
    {
        "id": "housing",
        "title": "住房管理",
        "status": "ready",
        "category": "life",
        "description": "房贷、租房、物业、水电燃气、维修报修。",
        "web_route": "/modules/housing",
        "miniapp_route": "/pages/webview/webview",
        "owner": "product",
    },
    {
        "id": "documents",
        "title": "证件管理",
        "status": "ready",
        "category": "life",
        "description": "身份证、护照、驾照、房产证、到期提醒。",
        "web_route": "/modules/documents",
        "miniapp_route": "/pages/webview/webview",
        "owner": "product",
    },
    {
        "id": "schedule",
        "title": "家庭日程",
        "status": "ready",
        "category": "core",
        "description": "生日、纪念日、节假日、接送安排与同步提醒。",
        "web_route": "/schedule",
        "miniapp_route": "/pages/webview/webview",
        "owner": "platform",
    },
    {
        "id": "chores",
        "title": "家务分工",
        "status": "ready",
        "category": "life",
        "description": "轮值表、家务分配、完成提醒、家庭协作。",
        "web_route": "/modules/chores",
        "miniapp_route": "/pages/webview/webview",
        "owner": "product",
    },
    {
        "id": "shopping",
        "title": "采购管理",
        "status": "ready",
        "category": "core",
        "description": "常买清单、库存、补货提醒、家庭采购协同。",
        "web_route": "/shopping",
        "miniapp_route": "/pages/webview/webview",
        "owner": "platform",
    },
    {
        "id": "health",
        "title": "健康管理",
        "status": "ready",
        "category": "life",
        "description": "体检报告、用药、慢病跟踪、复诊安排。",
        "web_route": "/modules/health",
        "miniapp_route": "/pages/webview/webview",
        "owner": "product",
    },
    {
        "id": "travel",
        "title": "旅行管理",
        "status": "ready",
        "category": "life",
        "description": "行程、预算、打包清单、预订信息。",
        "web_route": "/modules/travel",
        "miniapp_route": "/pages/webview/webview",
        "owner": "product",
    },
    {
        "id": "members",
        "title": "家庭成员",
        "status": "ready",
        "category": "core",
        "description": "家庭号、邀请、角色权限、成员联动统计。",
        "web_route": "/members",
        "miniapp_route": "/pages/webview/webview",
        "owner": "platform",
    },
    {
        "id": "photos",
        "title": "照片记忆",
        "status": "ready",
        "category": "memory",
        "description": "家庭照片上传、识别、标签和检索。",
        "web_route": "/photos",
        "miniapp_route": "/pages/webview/webview",
        "owner": "platform",
    },
    {
        "id": "knowledge",
        "title": "知识库",
        "status": "ready",
        "category": "memory",
        "description": "沉淀家庭资料、知识文档和可搜索问答。",
        "web_route": "/knowledge",
        "miniapp_route": "/pages/webview/webview",
        "owner": "platform",
    },
    {
        "id": "memory",
        "title": "记忆管理",
        "status": "ready",
        "category": "memory",
        "description": "管理家庭偏好、事实、会话摘要和长期记忆。",
        "web_route": "/memory",
        "miniapp_route": "/pages/webview/webview",
        "owner": "platform",
    },
    {
        "id": "skills",
        "title": "技能中心",
        "status": "ready",
        "category": "ai",
        "description": "管理 AI 助手的专业技能和使用状态。",
        "web_route": "/skills",
        "miniapp_route": "/pages/webview/webview",
        "owner": "platform",
    },
    {
        "id": "smarthome",
        "title": "智能家居",
        "status": "ready",
        "category": "integration",
        "description": "通过自然语言控制 Home Assistant 设备。",
        "web_route": "/smarthome",
        "miniapp_route": "/pages/webview/webview",
        "owner": "platform",
    },
    {
        "id": "mcp",
        "title": "MCP 协议",
        "status": "ready",
        "category": "integration",
        "description": "标准化工具发现和工具调用调试。",
        "web_route": "/mcp",
        "miniapp_route": "/pages/webview/webview",
        "owner": "platform",
    },
    {
        "id": "stats",
        "title": "统计信息",
        "status": "ready",
        "category": "core",
        "description": "查看家庭成员、任务、日程、采购和照片统计。",
        "web_route": "/stats",
        "miniapp_route": "/pages/webview/webview",
        "owner": "platform",
    },
    {
        "id": "notifications",
        "title": "消息通知",
        "status": "ready",
        "category": "core",
        "description": "查看任务、提醒、系统消息和未读通知。",
        "web_route": "/notifications",
        "miniapp_route": "/pages/webview/webview",
        "owner": "platform",
    },
]


@router.get("/modules")
def list_modules():
    return {
        "items": MODULES,
        "ready_count": sum(1 for item in MODULES if item["status"] == "ready"),
        "planned_count": sum(1 for item in MODULES if item["status"] != "ready"),
    }
